version: '3'

services:

  app:
    build:
      context: .
      dockerfile: fastapi.Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis
    ports:
      - "6379:6379"

  enum-worker:
    build:
      context: .
      dockerfile: enum_worker.Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
    entrypoint: ["python3","-u","enum_job_worker.py"]

  dnsx-resolve-worker:
    build:
      context: .
      dockerfile: enum_worker.Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
    entrypoint: ["python3","-u","dnsx-resolve_job_worker.py"]

  httpx-resolve-worker:
    build:
      context: .
      dockerfile: enum_worker.Dockerfile
    depends_on:
      - redis
    volumes:
      - .:/app
    entrypoint: ["python3","-u","httpx-resolve_job_worker.py"]
